version: '3'

services:
  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: extchatdb
      MYSQL_USER: chatadm
      MYSQL_PASSWORD: chatadmpass
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - chat_db_data:/var/lib/mysql
    restart: unless-stopped
  backend:
    image: chat_backend:latest
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: chatadm
      DB_PASSWORD: chatadmpass
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  frontend:
    image: chat_frontend:latest
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - backend
volumes:
  chat_db_data:
